
-include config.mk

PACKAGES = controlboard \
	wiicarutility \
	wiimotecar 

TARGET_NAME:=wiimotecarapp

EXECUTABLE_NAME:=$(TARGET_NAME)

LIBS=cwiid bluetooth

all compile build install debug: $(EXECUTABLE_NAME)

-include makedefs.mk
